imu_topic: /sensors/imu
roll_command_topic: /laser_roll_controller/command
pitch_command_topic: /laser_pitch_controller/command
buffer_size: 5
min_roll: -1.57
min_pitch: -1.57
max_roll: 1.57
max_pitch:  0.785
