min_command: 0.0
max_command: 0.18
movement_threshold: 0.005
lax_movement_threshold: 0.03
target_distance_threshold: 1.5
command_timeout: 15.0
linear_command_topic: /linear_elevator_controller/command
linear_motor_frame: linear_elevator_link
