action_name:
  - move_kinect_action
  - move_head_action
move_kinect_action:
  pitch_step: -0.2
  yaw_step: 0.7
  min_pitch: -0.7
  min_yaw: -1
  max_pitch: 0.75
  max_yaw: 1
  scan_rate: 1.0
  command_timeout: 10.0
  movement_threshold: 0.05
  lax_movement_threshold: 0.5
  pitch_command_topic: /kinect_pitch_controller/command
  yaw_command_topic: /kinect_yaw_controller/command
  pitch_joint_parent: linear_elevator_link
  pitch_joint_child: kinect_servo_link
  yaw_joint_parent: kinect_servo_link
  yaw_joint_child: kinect_base_link
  sensor_frame: kinect_frame
move_head_action:
  pitch_step: 0.4
  yaw_step: 0.5
  min_pitch: -1
  min_yaw: -1
  max_pitch: 1
  max_yaw: 1
  time_step: 1
  command_timeout: 10.0
  movement_threshold: 0.05
  lax_movement_threshold: 0.5
  pitch_command_topic: /linear_head_pitch_controller/command
  yaw_command_topic: /linear_head_yaw_controller/command
  pitch_joint_parent: linear_head_base_link
  pitch_joint_child: linear_head_main_link
  yaw_joint_parent: linear_elevator_link
  yaw_joint_child: linear_head_base_link
  sensor_frame: middle_thermal_frame
