action_name:
  - move_kinect_action
  - move_camera_effector_action
move_kinect_action:
  pitch_step: 0.3
  min_pitch: -0.785
  max_pitch: 0.785
  offset_pitch: -0.05
  yaw_step: 0.7
  min_yaw: -1.308
  max_yaw: 1.308
  offset_yaw: 0
  scan_rate: 1.0
  pitch_rate: 0.1
  command_timeout: 10.0
  movement_threshold: 0.05
  lax_movement_threshold: 0.25
  imu_topic: /sensors/imu_rpy
  buffer_size: 5
  pitch_command_topic: /kinect_pitch_controller/command
  yaw_command_topic: /kinect_yaw_controller/command
  pitch_joint_parent: kinect_pitch_servo_link
  pitch_joint_child: kinect_platform_link
  yaw_joint_parent: kinect_yaw_servo_link
  yaw_joint_child: kinect_pitch_servo_link
  sensor_frame: kinect_frame
move_camera_effector_action:
  pitch_step: 0.0
  min_pitch: -0.6
  max_pitch: 0.6
  offset_pitch: 0.0
  yaw_step: 0.7
  min_yaw: -1.3962
  max_yaw: 1.3962
  offset_yaw: 0.0
  scan_rate: 1.0
  pitch_rate: 0.1
  command_timeout: 10.0
  movement_threshold: 0.05
  lax_movement_threshold: 0.25
  imu_topic: /sensors/imu_rpy
  buffer_size: 5
  pitch_command_topic: /camera_effector/tilt_command
  yaw_command_topic: /camera_effector/pan_command
  pitch_joint_parent: camera_effector_tilt_link
  pitch_joint_child: pi_camera_link
  yaw_joint_parent: linear_actuator_link
  yaw_joint_child: camera_effector_pan_link
  sensor_frame: pi_camera_frame
